using System;
using System.Linq;
using System.Text;
using System.Text.Json;
using AiNetCodeNavigator.Mcp.Tools.Relationships;
using AiNetCodeNavigator.Mcp.Tools.Symbols;
using AiNetCodeNavigator.TestKit;
using AiNetCodeNavigator.TestKit.Builders;
using ModelContextProtocol.Protocol;
using static AiNetCodeNavigator.IntegrationTests.Mcp.IntegrationMcpAssertions;

namespace AiNetCodeNavigator.IntegrationTests.Mcp;

[Trait("Category", "Integration")]
public sealed class SourceRelationshipToolsContractTests
{
    [Fact]
    public async Task FindReferences_ResultCursorReconstructsAllMatchesAcrossPages()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-reference-pages-");
        var (target, project) = await CreateSourceProjectAsync(fixture);
        await using var testHost = InMemorySourceTestHost.Create(target, [project]);
        var relationships = new RelationshipTools(testHost.Runtime);

        var seen = new List<string>();
        string? cursor = null;
        var pageCount = 0;
        do
        {
            var response = await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: 4, resultCursor: cursor, maxResponseBytes: 65536, maxResponseTokens: 4096);
            AssertSuccessWithinBudget(response, 65536, 4096);
            using var document = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(response)));
            var root = document.RootElement;
            foreach (var item in root.GetProperty("references").EnumerateArray())
                seen.Add($"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("enclosingSymbolName").GetString()}");
            cursor = root.TryGetProperty("resultCursor", out var cursorValue)
                && cursorValue.ValueKind == System.Text.Json.JsonValueKind.String
                ? cursorValue.GetString()
                : null;
            pageCount++;
            Assert.InRange(pageCount, 1, 20);
        } while (cursor is not null);

        Assert.Equal(4, pageCount);
        Assert.Equal(16, seen.Count);
        Assert.Equal(16, seen.Distinct(StringComparer.Ordinal).Count());
        Assert.Contains(seen, item => item.Contains("Caller11.Invoke", StringComparison.Ordinal));
    }

    [Fact]
    public async Task FindImplementations_ResultCursorReconstructsAllMatchesAcrossPages()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-implementation-pages-");
        var (target, project) = await CreateSourceProjectAsync(fixture, implementationCount: 10);
        await using var testHost = InMemorySourceTestHost.Create(target, [project]);
        var relationships = new RelationshipTools(testHost.Runtime);

        var seen = new List<string>();
        string? cursor = null;
        var pageCount = 0;
        do
        {
            var response = await relationships.GetTypeRelations(target, "M:RelationshipProbe.Base.Run", "implementations",
                maxResults: 4, resultCursor: cursor, maxResponseBytes: 65536, maxResponseTokens: 4096);
            AssertSuccessWithinBudget(response, 65536, 4096);
            using var document = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(response)));
            var root = document.RootElement;
            foreach (var item in root.GetProperty("implementations").EnumerateArray())
                seen.Add($"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("symbolName").GetString()}");
            cursor = root.TryGetProperty("resultCursor", out var cursorValue)
                && cursorValue.ValueKind == System.Text.Json.JsonValueKind.String
                ? cursorValue.GetString()
                : null;
            pageCount++;
            Assert.InRange(pageCount, 1, 20);
        } while (cursor is not null);

        Assert.Equal(3, pageCount);
        Assert.Equal(11, seen.Count);
        Assert.Equal(11, seen.Distinct(StringComparer.Ordinal).Count());
        Assert.Contains(seen, item => int.Parse(item.Split(':')[1], System.Globalization.CultureInfo.InvariantCulture) > 40);
    }

    [Fact]
    public async Task RelationshipScopesFilterBeforeReferenceAndImplementationTotalsAndPages()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-relationship-scope-pages-");
        var testsSource = "namespace RelationshipProbe; public sealed class TargetTests { public int Invoke(Target target) => target.Read(); } "
            + "public sealed class TestImplementation : Base { public override int Run() => 3; }";
        var generatedSource = "// <auto-generated/>\nnamespace RelationshipProbe; public sealed class GeneratedCaller { public int Invoke(Target target) => target.Read(); } "
            + "public sealed class GeneratedImplementation : Base { public override int Run() => 4; }";
        var (target, project) = await CreateSourceProjectAsync(fixture, implementationCount: 3,
            additionalDocuments: [("RelationshipProbe.Tests.cs", testsSource), ("Generated.g.cs", generatedSource)]);
        var (otherTarget, otherProject) = await CreateSourceProjectAsync(fixture, "other", implementationCount: 3);
        await using var testHost = InMemorySourceTestHost.CreateForSolutions(
            [(target, [project]), (otherTarget, [otherProject])]);
        var relationships = new RelationshipTools(testHost.Runtime);
        var appDirectory = Path.Combine(fixture.DirectoryPath, "src", "App");

        foreach (var (scope, expectedTotal) in new[] { ("all", 6), ("production", 5), ("tests", 1) })
        {
            var hierarchyItems = new List<string>();
            string? hierarchyCursor = null;
            string? firstHierarchyCursor = null;
            int? hierarchyTotal = null;
            var hierarchyPages = 0;
            do
            {
                var hierarchyPage = await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
                    maxResults: 2, scopeType: scope, resultCursor: hierarchyCursor,
                    maxResponseBytes: 32768, maxResponseTokens: 4096);
                AssertSuccessWithinBudget(hierarchyPage, 32768, 4096);
                using var hierarchyDocument = JsonDocument.Parse(JsonBody(TextOf(hierarchyPage)));
                var hierarchyRoot = hierarchyDocument.RootElement;
                hierarchyTotal ??= hierarchyRoot.GetProperty("totalSubtypes").GetInt32();
                hierarchyItems.AddRange(hierarchyRoot.GetProperty("subtypes").EnumerateArray()
                    .Select(item => $"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("name").GetString()}"));
                hierarchyCursor = hierarchyRoot.TryGetProperty("resultCursor", out var cursorValue)
                    && cursorValue.ValueKind == JsonValueKind.String ? cursorValue.GetString() : null;
                firstHierarchyCursor ??= hierarchyCursor;
                hierarchyPages++;
                Assert.InRange(hierarchyPages, 1, 10);
            } while (hierarchyCursor is not null);

            Assert.Equal(expectedTotal, hierarchyTotal);
            Assert.Equal(expectedTotal, hierarchyItems.Count);
            Assert.Equal(expectedTotal, hierarchyItems.Distinct(StringComparer.Ordinal).Count());
            Assert.DoesNotContain(hierarchyItems, item => item.Contains("GeneratedImplementation", StringComparison.Ordinal));
            Assert.Equal(scope != "production", hierarchyItems.Any(item => item.Contains("TestImplementation", StringComparison.Ordinal)));
            Assert.Equal((expectedTotal + 1) / 2, hierarchyPages);
            if (scope == "all")
            {
                Assert.NotNull(firstHierarchyCursor);
                AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
                    maxResults: 2, scopeType: "tests", resultCursor: firstHierarchyCursor,
                    maxResponseBytes: 32768, maxResponseTokens: 4096),
                    "RESULT_CURSOR_ARGUMENT_MISMATCH", 32768, 4096);
            }
        }

        var references = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "references", "enclosingSymbolName", pageSize: 4, scope: "all");
        Assert.Equal(17, references.TotalCount);
        Assert.Equal(17, references.Items.Count);
        Assert.Equal(17, references.Items.Distinct(StringComparer.Ordinal).Count());
        Assert.True(references.Pages > 1);
        Assert.DoesNotContain(references.Items, item => item.Contains("GeneratedCaller", StringComparison.Ordinal));
        Assert.Contains(references.Items, item => item.Contains("TargetTests.Invoke", StringComparison.Ordinal));
        Assert.NotNull(references.FirstCursor);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 5, resultCursor: references.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 16384, 2048);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            scopeType: "tests", maxResults: 4, resultCursor: references.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 16384, 2048);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Base.Run",
            maxResults: 4, resultCursor: references.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 16384, 2048);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 4, resultCursor: "malformed-cursor", maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_EXPIRED", 16384, 2048);
        AssertErrorWithinBudget(await relationships.FindReferences(otherTarget, "M:RelationshipProbe.Target.Read",
            maxResults: 4, resultCursor: references.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 16384, 2048);

        var productionReferences = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "references", "enclosingSymbolName", pageSize: 4, scope: "production");
        Assert.Equal(16, productionReferences.TotalCount);
        Assert.Equal(16, productionReferences.Items.Count);
        Assert.True(productionReferences.Pages > 1);
        Assert.DoesNotContain(productionReferences.Items, item => item.Contains("TargetTests", StringComparison.Ordinal));

        var testReferences = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "references", "enclosingSymbolName", pageSize: 4, scope: "tests");
        Assert.Equal(1, testReferences.TotalCount);
        Assert.EndsWith(":TargetTests.Invoke", Assert.Single(testReferences.Items), StringComparison.Ordinal);

        var implementations = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.GetTypeRelations(target, "M:RelationshipProbe.Base.Run", "implementations",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "implementations", "symbolName", pageSize: 2, scope: "all");
        Assert.Equal(5, implementations.TotalCount);
        Assert.Equal(5, implementations.Items.Count);
        Assert.True(implementations.Pages > 1);
        Assert.DoesNotContain(implementations.Items, item => item.Contains("Generated.g.cs", StringComparison.Ordinal));
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "M:RelationshipProbe.Base.Run", "implementations",
            maxResults: 3, resultCursor: implementations.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 16384, 2048);

        var productionImplementations = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.GetTypeRelations(target, "M:RelationshipProbe.Base.Run", "implementations",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "implementations", "symbolName", pageSize: 2, scope: "production");
        Assert.Equal(4, productionImplementations.TotalCount);
        Assert.DoesNotContain(productionImplementations.Items, item => item.Contains("RelationshipProbe.Tests.cs", StringComparison.Ordinal));

        var testImplementations = await ReadRelationshipPagesAsync(
            (cursor, pageSize, scope, bytes, tokens, continuation) => relationships.GetTypeRelations(target, "M:RelationshipProbe.Base.Run", "implementations",
                maxResults: pageSize, scopeType: scope, resultCursor: cursor,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation),
            "implementations", "symbolName", pageSize: 2, scope: "tests");
        Assert.Equal(1, testImplementations.TotalCount);
        Assert.Contains("RelationshipProbe.Tests.cs", Assert.Single(testImplementations.Items), StringComparison.Ordinal);

        var sourcePath = Path.Combine(appDirectory, "Relationships.cs");
        await File.AppendAllTextAsync(sourcePath, "\nnamespace RelationshipProbe; public sealed class SnapshotMarker { }");
        File.SetLastWriteTimeUtc(sourcePath, DateTime.UtcNow.AddSeconds(2));
        var staleCursorResult = await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 4, resultCursor: references.FirstCursor, maxResponseBytes: 16384, maxResponseTokens: 2048);
        Assert.Contains("Repeat the query against the current snapshot", TextOf(staleCursorResult), StringComparison.Ordinal);
        AssertErrorWithinBudget(staleCursorResult, "STALE_SNAPSHOT", 16384, 2048);
    }

    [Fact]
    public async Task TypeHierarchy_ResultCursorReconstructsAllDerivedTypesAcrossPages()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-hierarchy-pages-");
        var (target, project) = await CreateSourceProjectAsync(fixture, subtypeCount: 10);
        var copiedTarget = Path.Combine(fixture.DirectoryPath, "Relationships-copy.slnx");
        File.Copy(target, copiedTarget);
        await using var testHost = InMemorySourceTestHost.CreateForSolutions([(target, [project]), (copiedTarget, [project])]);
        var relationships = new RelationshipTools(testHost.Runtime);
        var scanners = new List<string>();
        relationships.BeforeTypeRelationScanForTesting = scanners.Add;
        var broadResponse = await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 100, maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(broadResponse, 65536, 4096);
        using var broadDocument = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(broadResponse)));
        var expected = broadDocument.RootElement.GetProperty("subtypes").EnumerateArray()
            .Select(item => $"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("name").GetString()}")
            .ToArray();

        var seen = new List<string>();
        string? cursor = null;
        string? firstCursor = null;
        var pageCount = 0;
        do
        {
            var response = await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
                maxResults: 4, resultCursor: cursor, maxResponseBytes: 65536, maxResponseTokens: 4096);
            AssertSuccessWithinBudget(response, 65536, 4096);
            using var document = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(response)));
            var root = document.RootElement;
            foreach (var item in root.GetProperty("subtypes").EnumerateArray())
                seen.Add($"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("name").GetString()}");
            cursor = root.TryGetProperty("resultCursor", out var cursorValue)
                && cursorValue.ValueKind == System.Text.Json.JsonValueKind.String
                ? cursorValue.GetString()
                : null;
            firstCursor ??= cursor;
            pageCount++;
            Assert.InRange(pageCount, 1, 20);
        } while (cursor is not null);

        Assert.Equal(3, pageCount);
        Assert.Equal(12, broadDocument.RootElement.GetProperty("totalSubtypes").GetInt32());
        Assert.Equal(12, seen.Count);
        Assert.Equal(12, seen.Distinct(StringComparer.Ordinal).Count());
        Assert.Equal(expected, seen);
        Assert.Contains(seen, item => item.Contains("Subtype09", StringComparison.Ordinal));
        Assert.NotNull(firstCursor);
        Assert.All(scanners, scanner => Assert.Equal("hierarchy", scanner));
        scanners.Clear();
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "implementations",
            maxResults: 4, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
        AssertSuccessWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "implementations",
            maxResults: 4, maxResponseBytes: 65536, maxResponseTokens: 4096), 65536, 4096);
        Assert.Equal(["implementations"], scanners);
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 4, scopeType: "all", resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 4, includeGenerated: false, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);

        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 5, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 4, resultCursor: "malformed-cursor", maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_EXPIRED", 65536, 4096);
        AssertErrorWithinBudget(await relationships.GetTypeRelations(copiedTarget, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 4, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
        var sourcePath = Path.Combine(fixture.DirectoryPath, "src", "App", "Relationships.cs");
        await File.AppendAllTextAsync(sourcePath, "\nnamespace RelationshipProbe; public sealed class SnapshotMarker { }");
        File.SetLastWriteTimeUtc(sourcePath, DateTime.UtcNow.AddSeconds(2));
        AssertErrorWithinBudget(await relationships.GetTypeRelations(target, "T:RelationshipProbe.Base", "hierarchy",
            maxResults: 4, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "STALE_SNAPSHOT", 65536, 4096);
    }

    [Fact]
    public async Task ReferencesSummary_ResultCursorReconstructsAllSitesAcrossPages()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-impact-pages-");
        var (target, project) = await CreateSourceProjectAsync(fixture);
        await using var testHost = InMemorySourceTestHost.Create(target, [project]);
        var relationships = new RelationshipTools(testHost.Runtime);
        var broadResponse = await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 100, maxResponseBytes: 65536, maxResponseTokens: 4096, includeSummary: true);
        AssertSuccessWithinBudget(broadResponse, 65536, 4096);
        var broadPages = await IntegrationMcpAssertions.ReadOuterResponsePagesAsync(
            (bytes, tokens, continuation) => relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: 100, maxResponseBytes: bytes, maxResponseTokens: tokens,
                continuationToken: continuation, includeSummary: true), 65536, 4096);
        using var broadDocument = System.Text.Json.JsonDocument.Parse(IntegrationMcpAssertions.BodyOf(broadPages.Text));
        var expected = broadDocument.RootElement.GetProperty("references").EnumerateArray()
            .Select(item => $"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("enclosingSymbolName").GetString()}")
            .ToArray();

        var seen = new List<string>();
        string? cursor = null;
        string? firstCursor = null;
        var pages = 0;
        int? total = null;
        do
        {
            var response = await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
                maxResults: 4, resultCursor: cursor, maxResponseBytes: 65536, maxResponseTokens: 4096, includeSummary: true);
            AssertSuccessWithinBudget(response, 65536, 4096);
            using var document = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(response)));
            var root = document.RootElement;
            Assert.Equal(broadDocument.RootElement.GetProperty("summary").GetRawText(), root.GetProperty("summary").GetRawText());
            total ??= root.GetProperty("summary").GetProperty("totalReferenceSiteCount").GetInt32();
            foreach (var item in root.GetProperty("references").EnumerateArray())
                seen.Add($"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty("enclosingSymbolName").GetString()}");
            cursor = root.TryGetProperty("resultCursor", out var cursorValue)
                && cursorValue.ValueKind == System.Text.Json.JsonValueKind.String ? cursorValue.GetString() : null;
            firstCursor ??= cursor;
            pages++;
            Assert.InRange(pages, 1, 20);
        } while (cursor is not null);

        Assert.True(total > 4);
        Assert.Equal(total, broadDocument.RootElement.GetProperty("summary").GetProperty("totalReferenceSiteCount").GetInt32());
        Assert.Equal(total, seen.Count);
        Assert.Equal(seen.Count, seen.Distinct(StringComparer.Ordinal).Count());
        Assert.Equal(expected, seen);
        Assert.NotNull(firstCursor);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 4, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
        AssertErrorWithinBudget(await relationships.FindReferences(target, "M:RelationshipProbe.Target.Read",
            maxResults: 5, resultCursor: firstCursor, maxResponseBytes: 65536, maxResponseTokens: 4096, includeSummary: true),
            "RESULT_CURSOR_ARGUMENT_MISMATCH", 65536, 4096);
    }

    [Fact]
    public async Task DependencyGraph_TraversesTargetInDocumentWindowAfterOneThousand()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-relationship-window-");
        var (target, project) = await CreateSourceProjectAsync(fixture, fillerCount: 1000);
        await using var testHost = InMemorySourceTestHost.Create(target, [project]);
        var relationships = new RelationshipTools(testHost.Runtime);
        var graph = await relationships.DependencyGraph(target, symbolIdentifier: "T:RelationshipProbe.LateRoot",
            direction: "outgoing", depth: 1, maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(graph, 65536, 4096);
        using var document = JsonDocument.Parse(JsonBody(TextOf(graph)));
        var root = document.RootElement;
        var edges = root.GetProperty("typeDependencies").EnumerateArray().ToArray();
        Assert.Contains(edges, edge => edge.GetProperty("fromTypeName").GetString() == "LateRoot"
            && edge.GetProperty("toTypeName").GetString() == "LaterDependency");
        Assert.True(root.GetProperty("isComplete").GetBoolean(), TextOf(graph));
    }

    [Fact]
    public async Task DependencyGraph_UsesStableReferenceProjectOwnerForEqualGenericTypeNames()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-relationship-identity-");
        var (target, projects) = await CreateDuplicateGenericWorkspaceAsync(fixture);
        await using var testHost = InMemorySourceTestHost.Create(target, projects);
        var relationships = new RelationshipTools(testHost.Runtime);
        var symbols = new SymbolTools(testHost.Runtime);
        var found = await symbols.FindSymbol(target, pattern: "Box", kind: "class", maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(found, 65536, 4096);
        using var foundDocument = System.Text.Json.JsonDocument.Parse(JsonBody(TextOf(found)));
        var firstHandoff = foundDocument.RootElement.GetProperty("results").EnumerateArray()
            .SelectMany(result => result.GetProperty("entries").EnumerateArray())
            .Single(entry => entry.GetProperty("filePath").GetString()!.Contains("src/First/Box.cs", StringComparison.Ordinal))
            .GetProperty("handoffId").GetString()!;
        var graph = await relationships.DependencyGraph(target, symbolIdentifier: firstHandoff,
            direction: "outgoing", depth: 1, maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(graph, 65536, 4096);
        Assert.Contains("src/First/Box.cs", TextOf(graph), StringComparison.Ordinal);
        Assert.Contains("FirstDependency", TextOf(graph), StringComparison.Ordinal);
        Assert.DoesNotContain("src/Second/Box.cs", TextOf(graph), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, graph, "FirstDependency",
            (bytes, tokens, continuation) => relationships.DependencyGraph(target, symbolIdentifier: firstHandoff,
                direction: "outgoing", depth: 1, maxResponseBytes: bytes, maxResponseTokens: tokens,
                continuationToken: continuation));
    }

    [Fact]
    public async Task SourceRelationshipHandlersReturnNavigableResultsErrorsAndBoundedProjections()
    {
        using var fixture = TestTempDirectory.Create("ainet-source-relationships-");
        var (target, project) = await CreateSourceProjectAsync(fixture);
        await using var testHost = InMemorySourceTestHost.Create(target, [project]);
        var relationships = new RelationshipTools(testHost.Runtime);
        var symbols = new SymbolTools(testHost.Runtime);
        const string runId = "M:RelationshipProbe.Entry.Run";
        const string targetId = "M:RelationshipProbe.Target.Read";
        const string baseId = "T:RelationshipProbe.Base";
        const string contractMethodId = "M:RelationshipProbe.IWorker.Work";
        const string genericId = "T:RelationshipProbe.GenericBox`1";
        var longCallId = "M:RelationshipProbe.Target.LongCaller" + new string('X', 500);

        var tree = await relationships.GetCallTree(target, runId, direction: "outgoing", depth: 1,
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(tree, 65536, 4096);
        Assert.Contains("Target.Read", TextOf(tree), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, tree, "public int Read",
            (bytes, tokens, continuation) => relationships.GetCallTree(target, runId, direction: "outgoing", depth: 1,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));

        var references = await relationships.FindReferences(target, targetId,
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(references, 65536, 4096);
        Assert.Contains("Entry.Run", TextOf(references), StringComparison.Ordinal);
        Assert.Contains("column", TextOf(references), StringComparison.OrdinalIgnoreCase);
        await AssertHandoffReachesBodyAsync(symbols, target, references, "target.Read",
            (bytes, tokens, continuation) => relationships.FindReferences(target, targetId,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));

        var hierarchy = await relationships.GetTypeRelations(target, baseId, "hierarchy",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(hierarchy, 65536, 4096);
        Assert.Contains("Derived", TextOf(hierarchy), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, hierarchy, "Derived",
            (bytes, tokens, continuation) => relationships.GetTypeRelations(target, baseId, "hierarchy",
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));

        var implementations = await relationships.GetTypeRelations(target, contractMethodId, "implementations",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(implementations, 65536, 4096);
        Assert.Contains("Derived.Work", TextOf(implementations), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, implementations, "public int Work",
            (bytes, tokens, continuation) => relationships.GetTypeRelations(target, contractMethodId, "implementations",
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));

        var dependencies = await relationships.DependencyGraph(target, symbolIdentifier: genericId,
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(dependencies, 65536, 4096);
        Assert.Contains("GenericBox", TextOf(dependencies), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, dependencies, "GenericBox",
            (bytes, tokens, continuation) => relationships.DependencyGraph(target, symbolIdentifier: genericId,
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));
        var fileDependencies = await relationships.DependencyGraph(target, filePath: "src/App/Relationships.cs",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(fileDependencies, 65536, 4096);
        Assert.Contains("Entry", TextOf(fileDependencies), StringComparison.Ordinal);
        Assert.Contains("Derived", TextOf(fileDependencies), StringComparison.Ordinal);
        await AssertHandoffReachesBodyAsync(symbols, target, fileDependencies, "public static int Invoke",
            (bytes, tokens, continuation) => relationships.DependencyGraph(target, filePath: "src/App/Relationships.cs",
                maxResponseBytes: bytes, maxResponseTokens: tokens, continuationToken: continuation));

        var origin = await relationships.ResolveTypeOrigin(target, typeName: "RelationshipProbe.Derived",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(origin, 65536, 4096);
        Assert.Contains("assemblyOrigin", TextOf(origin), StringComparison.Ordinal);
        Assert.Contains("source", TextOf(origin), StringComparison.Ordinal);
        Assert.Contains("RelationshipProbe.App", TextOf(origin), StringComparison.Ordinal);
        var originByIdentifier = await relationships.ResolveTypeOrigin(target, symbolIdentifier: "T:RelationshipProbe.Derived",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        AssertSuccessWithinBudget(originByIdentifier, 65536, 4096);
        Assert.Contains("RelationshipProbe.Derived", TextOf(originByIdentifier), StringComparison.Ordinal);

        var invalidDirection = await relationships.GetCallTree(target, "h:unknown", direction: "sideways",
            maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(invalidDirection, "INVALID_ARGUMENT", 16384, 2048);
        Assert.Contains("direction", TextOf(invalidDirection), StringComparison.Ordinal);
        var unknownReference = await relationships.FindReferences(target, "h:unknown",
            maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(unknownReference, "INVALID_SYMBOL_REFERENCE", 16384, 2048);
        var missingDependencySelection = await relationships.DependencyGraph(target,
            maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(missingDependencySelection, "INVALID_ARGUMENT", 16384, 2048);
        var conflictingDependencySelection = await relationships.DependencyGraph(target, filePath: "src/App/Relationships.cs",
            symbolIdentifier: genericId, maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(conflictingDependencySelection, "INVALID_ARGUMENT", 16384, 2048);
        var missingOriginSelection = await relationships.ResolveTypeOrigin(target,
            maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(missingOriginSelection, "INVALID_ARGUMENT", 16384, 2048);
        var conflictingOriginSelection = await relationships.ResolveTypeOrigin(target, symbolIdentifier: "T:RelationshipProbe.Derived",
            typeName: "RelationshipProbe.Derived", maxResponseBytes: 16384, maxResponseTokens: 2048);
        AssertErrorWithinBudget(conflictingOriginSelection, "INVALID_ARGUMENT", 16384, 2048);

        var longCallAscii = await relationships.GetCallTree(target, longCallId, direction: "outgoing", depth: 1, format: "ascii",
            maxResponseBytes: 65536, maxResponseTokens: 4096);
        await AssertProjectionMatchesAsync("get_call_tree ASCII", longCallAscii,
            (bytes, tokens, operation, continuation) => relationships.GetCallTree(target, longCallId, direction: "outgoing", depth: 1,
                format: "ascii", maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation),
            requireTokenRecovery: true);
        await AssertProjectionMatchesAsync("get_call_tree Mermaid",
            await relationships.GetCallTree(target, longCallId, direction: "outgoing", depth: 1, format: "mermaid",
                maxResponseBytes: 65536, maxResponseTokens: 4096),
            (bytes, tokens, operation, continuation) => relationships.GetCallTree(target, longCallId, direction: "outgoing", depth: 1,
                format: "mermaid", maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation),
            requireTokenRecovery: true);
        await AssertProjectionMatchesAsync("find_references", references,
            (bytes, tokens, operation, continuation) => relationships.FindReferences(target, targetId,
                maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation));
        await AssertProjectionMatchesAsync("get_type_relations", hierarchy,
            (bytes, tokens, operation, continuation) => relationships.GetTypeRelations(target, baseId, "hierarchy",
                maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation));
        await AssertProjectionMatchesAsync("get_type_relations", implementations,
            (bytes, tokens, operation, continuation) => relationships.GetTypeRelations(target, contractMethodId, "implementations",
                maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation));
        await AssertProjectionMatchesAsync("dependency_graph", dependencies,
            (bytes, tokens, operation, continuation) => relationships.DependencyGraph(target, symbolIdentifier: genericId,
                maxResponseBytes: bytes, maxResponseTokens: tokens,
                operationToken: operation, continuationToken: continuation));
        await AssertProjectionMatchesAsync("resolve_type_origin", origin,
            (bytes, tokens, operation, continuation) => relationships.ResolveTypeOrigin(target, typeName: "RelationshipProbe.Derived",
                maxResponseBytes: bytes, maxResponseTokens: tokens, operationToken: operation, continuationToken: continuation));
    }

    private static async Task AssertProjectionMatchesAsync(
        string label,
        CallToolResult broadResult,
        Func<int, int?, string?, string?, Task<CallToolResult>> invoke,
        bool requireTokenRecovery = false)
    {
        AssertSuccessWithinBudget(broadResult, 65536, 4096);
        var expected = BodyOf(TextOf(broadResult));
        var byteProjection = await ReadProjectionAsync(label + " byte", invoke, expected,
            requireTokenRecovery ? 512 : 16384, 4096);
        Assert.True(byteProjection.Pages >= 1, label);
        var tokenProjection = await ReadProjectionAsync(label + " token", invoke, expected,
            65536, requireTokenRecovery ? 120 : 4096);
        if (requireTokenRecovery)
            Assert.True(tokenProjection.MinimumRecoveryObserved, $"{label} did not execute the advertised minimum-token recovery path.");
    }

    private static async Task<(int Pages, bool MinimumRecoveryObserved)> ReadProjectionAsync(
        string label,
        Func<int, int?, string?, string?, Task<CallToolResult>> invoke,
        string expected,
        int responseBytes,
        int responseTokens)
    {
        var output = new StringBuilder();
        var pages = 0;
        var minimumRecoveryObserved = false;
        var awaitingAdvertisedRetry = false;
        string? operation = null;
        string? continuation = null;
        var currentBytes = responseBytes;
        var currentTokens = responseTokens;
        var result = await invoke(currentBytes, currentTokens, operation, continuation);
        for (var request = 0; request < 1_000; request++)
        {
            var text = TextOf(result);
            AssertBudget(text, currentBytes, currentTokens);
            if (result.IsError == true && text.Contains("RESPONSE_BUDGET_TOO_SMALL", StringComparison.Ordinal))
            {
                Assert.False(awaitingAdvertisedRetry,
                    $"{label} returned another budget failure after retrying its advertised minimum pair: {text}");
                minimumRecoveryObserved = true;
                awaitingAdvertisedRetry = true;
                currentBytes = ReadBudget(text, "minimumResponseBytes");
                currentTokens = ReadBudget(text, "minimumResponseTokens");
                Assert.InRange(currentBytes, 512, 65536);
                Assert.True(currentTokens >= 1,
                    $"{label} advertised a recovery pair outside the public budget range: {text}");
                result = await invoke(currentBytes, currentTokens, operation, continuation);
                continue;
            }
            if (TryReadToken(text, "operationToken", out var pending))
            {
                operation = pending;
                await Task.Delay(50);
                result = await invoke(currentBytes, currentTokens, operation, continuation);
                continue;
            }
            if (text.Contains("operation=retry", StringComparison.Ordinal))
            {
                await Task.Delay(50);
                result = await invoke(currentBytes, currentTokens, operation, continuation);
                continue;
            }

            Assert.False(result.IsError ?? false, $"{label}: {text}");
            AssertBudget(text, currentBytes, currentTokens);
            output.Append(BodyOf(text));
            pages++;
            operation = null;
            awaitingAdvertisedRetry = false;
            if (!TryReadToken(text, "continuationToken", out continuation))
            {
                Assert.Equal(expected, output.ToString());
                return (pages, minimumRecoveryObserved);
            }
            currentBytes = responseBytes;
            currentTokens = responseTokens;
            result = await invoke(currentBytes, currentTokens, operation, continuation);
        }
        throw new Xunit.Sdk.XunitException($"{label} did not reach a final response page.");
    }

    private static async Task AssertHandoffReachesBodyAsync(
        SymbolTools symbols,
        string target,
        CallToolResult result,
        string expectedFragment,
        Func<int, int?, string?, Task<CallToolResult>> readContinuation)
    {
        var pages = await ReadOuterResponsePagesAsync(readContinuation, 65536, 4096);
        Assert.Equal(BodyOf(TextOf(result)), BodyOf(pages.FirstPage));
        var handoffs = FindHandoffs(pages.Text);
        Assert.NotEmpty(handoffs);
        var bodies = new List<string>();
        foreach (var handoff in handoffs)
        {
            var body = await symbols.GetSymbolBody(target, [handoff], maxResponseBytes: 16384, maxResponseTokens: 2048);
            if (body.IsError == true) { bodies.Add(TextOf(body)); continue; }
            AssertSuccessWithinBudget(body, 16384, 2048);
            var bodyText = TextOf(body);
            if (bodyText.Contains(expectedFragment, StringComparison.Ordinal)) return;
            bodies.Add(bodyText);
        }
        Assert.Fail($"No relationship handoff resolved to a body containing '{expectedFragment}'.\n{TextOf(result)}\nBodies:\n{string.Join("\n---\n", bodies)}");
    }

    private static string[] FindHandoffs(string text)
        => IntegrationMcpAssertions.ReadStableReferences(text);

    private static string ReadHandoffFromLine(string line)
    {
        const string marker = "[handoff: ";
        var start = line.IndexOf(marker, StringComparison.Ordinal);
        Assert.True(start >= 0, line);
        start += marker.Length;
        var end = line.IndexOf(']', start);
        Assert.True(end > start, line);
        return line[start..end];
    }

    private static async Task<(string Target, ProjectSpec Project)> CreateSourceProjectAsync(
        TestTempDirectory fixture,
        string directoryName = "",
        int fillerCount = 0,
        int implementationCount = 0,
        int subtypeCount = 0,
        IReadOnlyList<(string FileName, string Content)>? additionalDocuments = null)
    {
        var root = Path.Combine(fixture.DirectoryPath, directoryName);
        var solution = Path.Combine(root, "Relationships.slnx");
        var projectDirectory = Path.Combine(root, "src", "App");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(solution, string.Empty);
        var callerDeclarations = string.Join("\n", Enumerable.Range(0, 12).Select(index =>
            $"public static class Caller{index:D2} {{ public static int Invoke(Target target) => target.Read(); }}"));
        var implementationDeclarations = string.Join("\n", Enumerable.Range(0, implementationCount).Select(index =>
            $"public sealed class Implementation{index:D2} : Base {{ public override int Run() => 1; }}"));
        var subtypeDeclarations = string.Join("\n", Enumerable.Range(0, subtypeCount).Select(index =>
            $"public sealed class Subtype{index:D2} : Base {{ }}"));
        var source = $$"""
            namespace RelationshipProbe;
            public interface IWorker { int Work(); }
            public class Base { public virtual int Run() => 1; }
            public class Target : Base
            {
                public int Read() => 2;
                public void LongCaller{{new string('X', 500)}}() => _ = Read();
            }
            public sealed class Derived : Target, IWorker
            {
                public override int Run() => Read();
                public int Work() => Run();
            }
            public sealed class GenericBox<T> { public T Value = default!; }
            public sealed class GenericConsumer { public GenericBox<string> Box = new(); }
            public sealed class Entry
            {
                public int Run()
                {
                    var target = new Derived();
                    var first = target.Read();
                    var second = target.Read();
                    return first + second;
                }
            }
            {{callerDeclarations}}
            {{implementationDeclarations}}
            {{subtypeDeclarations}}
            public static class Trigger
            {
                public static void Start() { new Entry().Run(); }
            }
            """;
        var documents = new List<(string FileName, string Content)>();
        documents.Add((Path.Combine(projectDirectory, "Relationships.cs"), source));
        foreach (var index in Enumerable.Range(0, fillerCount))
            documents.Add((Path.Combine(projectDirectory, $"A{index:D4}.cs"), $"namespace Filler{index:D4}; public sealed class Filler{index:D4} {{ }}"));
        if (fillerCount > 0)
            documents.Add((Path.Combine(projectDirectory, "ZLater.cs"),
                "namespace RelationshipProbe; public sealed class LaterDependency { } public sealed class LateRoot { public LaterDependency Value { get; set; } = new(); }"));
        foreach (var (fileName, content) in additionalDocuments ?? [])
            documents.Add((Path.Combine(projectDirectory, fileName), content));
        foreach (var (fileName, content) in documents)
            await File.WriteAllTextAsync(fileName, content);
        var project = new ProjectSpec("RelationshipProbe.App", documents,
            VirtualProjectDirectory: Path.GetRelativePath(root, projectDirectory));
        return (solution, project);
    }

    private static async Task<(int TotalCount, List<string> Items, int Pages, string? FirstCursor)> ReadRelationshipPagesAsync(
        Func<string?, int, string, int, int?, string?, Task<CallToolResult>> invoke,
        string collectionName,
        string identityField,
        int pageSize,
        string scope)
    {
        var items = new List<string>();
        string? cursor = null;
        string? firstCursor = null;
        int? totalCount = null;
        var pages = 0;
        do
        {
            var pageBytes = cursor is null ? 16384 : 32768;
            var pageTokens = cursor is null ? 2048 : 4096;
            var responsePages = await ReadOuterResponsePagesAsync(
                (bytes, tokens, continuation) => invoke(continuation is null ? cursor : null,
                    pageSize, scope, bytes, tokens, continuation),
                pageBytes, pageTokens);
            using var document = ParseJsonWithDiagnostics(JsonBody(responsePages.Text),
                $"Relationship {collectionName} page (scope={scope}, pageSize={pageSize}, domainCursor={cursor ?? "<first>"}, outerPages={responsePages.Pages}, budgets={pageBytes}/{pageTokens})");
            var root = document.RootElement;
            totalCount ??= root.GetProperty("totalCount").GetInt32();
            foreach (var item in root.GetProperty(collectionName).EnumerateArray())
                items.Add($"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty(identityField).GetString()}");
            cursor = root.TryGetProperty("resultCursor", out var cursorValue)
                && cursorValue.ValueKind == JsonValueKind.String ? cursorValue.GetString() : null;
            firstCursor ??= cursor;
            pages++;
            Assert.InRange(pages, 1, 20);
        } while (cursor is not null);
        var broadPages = await ReadOuterResponsePagesAsync(
            (bytes, tokens, continuation) => invoke(null, 100, scope, bytes, tokens, continuation), 65536, 4096);
        using var broadDocument = ParseJsonWithDiagnostics(JsonBody(broadPages.Text),
            $"Relationship {collectionName} broad page (scope={scope}, pageSize=100, outerPages={broadPages.Pages}, budgets=65536/4096)");
        var broadRoot = broadDocument.RootElement;
        var broadItems = broadRoot.GetProperty(collectionName).EnumerateArray()
            .Select(item => $"{item.GetProperty("filePath").GetString()}:{item.GetProperty("line").GetInt32()}:{item.GetProperty(identityField).GetString()}")
            .ToList();
        Assert.Equal(totalCount, broadRoot.GetProperty("totalCount").GetInt32());
        Assert.Equal(broadItems, items);
        return (totalCount ?? 0, items, pages, firstCursor);
    }

    private static string JsonBody(string text)
    {
        var start = text.IndexOf('{');
        Assert.True(start >= 0, text);
        return text[start..];
    }

    private static async Task<(string Target, ProjectSpec[] Projects)> CreateDuplicateGenericWorkspaceAsync(TestTempDirectory fixture)
    {
        var root = fixture.DirectoryPath;
        var solution = Path.Combine(root, "DuplicateGenericTypes.slnx");
        Directory.CreateDirectory(Path.Combine(root, "src", "First"));
        Directory.CreateDirectory(Path.Combine(root, "src", "Second"));
        await File.WriteAllTextAsync(solution, string.Empty);
        const string firstSource = "namespace Duplicate; public sealed class Box<T> { public FirstDependency Value { get; set; } = new(); } public sealed class FirstDependency { }";
        const string secondSource = "namespace Duplicate; public sealed class Box<T> { public SecondDependency Value { get; set; } = new(); } public sealed class SecondDependency { }";
        var firstFile = Path.Combine(root, "src", "First", "Box.cs");
        var secondFile = Path.Combine(root, "src", "Second", "Box.cs");
        await File.WriteAllTextAsync(firstFile, firstSource);
        await File.WriteAllTextAsync(secondFile, secondSource);
        return (solution,
        [
            new ProjectSpec("First", [(firstFile, firstSource)], VirtualProjectDirectory: "src/First", AssemblyName: "RelationshipProbe.App"),
            new ProjectSpec("Second", [(secondFile, secondSource)], VirtualProjectDirectory: "src/Second", AssemblyName: "RelationshipProbe.App")
        ]);
    }
}
