#nullable enable

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AiNetCodeNavigator.Core.Symbols;

/// <summary>Applies the generated-source classification used by symbol navigation.</summary>
internal static class GeneratedDocumentDetector
{
    public static async Task<bool> IsGeneratedDocumentAsync(Document document, CancellationToken cancellationToken)
    {
        var path = (document.FilePath ?? document.Name).Replace('\\', '/');
        if (path.Contains("/obj/", StringComparison.OrdinalIgnoreCase)
            || path.StartsWith("obj/", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var text = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
        var headerLineCount = Math.Min(text.Lines.Count, 5);
        for (var lineNumber = 0; lineNumber < headerLineCount; lineNumber++)
        {
            if (text.Lines[lineNumber].ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) return true;
        }

        var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
        var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
        if (root is null || semanticModel is null) return false;

        foreach (var declaration in root.DescendantNodesAndSelf().OfType<MemberDeclarationSyntax>())
        {
            cancellationToken.ThrowIfCancellationRequested();
            var symbol = semanticModel.GetDeclaredSymbol(declaration, cancellationToken);
            if (symbol?.GetAttributes().Any(attribute =>
                    attribute.AttributeClass?.Name is "GeneratedCodeAttribute" or "GeneratedCode") == true)
            {
                return true;
            }
        }

        return false;
    }
}
