<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\AiNetCodeNavigator.Core\AiNetCodeNavigator.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AiNetCodeNavigator.FastTests" />
    <InternalsVisibleTo Include="AiNetCodeNavigator.IntegrationTests" />
  </ItemGroup>

</Project>
