<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AiNetCodeNavigator.Core\AiNetCodeNavigator.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AiNetCodeNavigator.FastTests" />
  </ItemGroup>
</Project>
