<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Version>1.0.13</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <ProjectReference Include="..\AiNetCodeNavigator.Core\AiNetCodeNavigator.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AiNetCodeNavigator.FastTests" />
  </ItemGroup>
</Project>
